/** The exercise database — movements with steps, demos and muscle maps. */

export interface Exercise {
  /** Muscles worked, e.g. "Chest · Triceps · Front delts". */
  m: string;
  /** Prescribed sets × reps, e.g. "4 × 6–8". */
  sr: string;
  steps: string[];
  tip: string;
  /** Equipment ids required (keys into EQUIPMENT). */
  eq: string[];
  /** Alternative exercise names to swap to. */
  alt: string[];
  /** YouTube video id for the form tutorial, if bundled. */
  vid?: string;
  /** Cable-attachment guidance, if relevant. */
  att?: string[];
  /** Lower-body movement → progress in larger 5 kg / 10 lb jumps. */
  lower?: boolean;
  /** Mobility / stretch — no load or reps to log, just hold and breathe. */
  mobility?: boolean;
}

export const EX: Record<string, Exercise> = {
  'Barbell Bench Press': {
    m: 'Chest · Triceps · Front delts',
    sr: '4 × 6–8',
    steps: [
      'Lie flat with eyes under the bar, feet planted, shoulder blades pinched back and down.',
      'Grip slightly wider than shoulder width and unrack with straight arms.',
      'Lower the bar under control to mid-chest, elbows tucked about 45°.',
      'Press back up in a slight arc until arms are locked out.',
    ],
    tip: 'Keep your butt on the bench and drive your feet into the floor for stability.',
    eq: ['barbell', 'bench'],
    alt: ['Incline Dumbbell Press', 'Push-Up'],
    vid: '4Y2ZdHCOXok',
  },
  'Incline Dumbbell Press': {
    m: 'Upper chest · Front delts · Triceps',
    sr: '3 × 8–10',
    steps: [
      'Set the bench to a 30–45° incline and sit back with dumbbells at shoulder level.',
      'Press the dumbbells up and slightly together until arms are extended.',
      'Lower slowly until you feel a stretch across the upper chest.',
      'Keep wrists stacked over elbows the whole time.',
    ],
    tip: "Don't set the incline too steep — past 45° it becomes a shoulder press.",
    eq: ['dumbbell', 'bench'],
    alt: ['Push-Up'],
    vid: '8fXfwG4ftaQ',
  },
  'Overhead Press': {
    m: 'Shoulders · Triceps · Core',
    sr: '4 × 6–8',
    steps: [
      'Stand with the bar at collarbone height, grip just outside shoulders.',
      "Brace your core and glutes so your lower back doesn't arch.",
      'Press the bar straight up, moving your head slightly back out of the way.',
      'Lock out overhead with biceps by your ears, then lower under control.',
    ],
    tip: 'Squeeze your glutes hard — it protects your lower back.',
    eq: ['barbell'],
    alt: ['Seated Dumbbell Shoulder Press'],
    vid: 'hG6sWbZmW1c',
  },
  'Seated Dumbbell Shoulder Press': {
    m: 'Shoulders · Triceps',
    sr: '3 × 8–12',
    steps: [
      'Sit on an upright bench, dumbbells at shoulder height, palms forward.',
      'Press up until arms are extended without slamming the weights together.',
      'Lower with control until elbows are just below shoulder level.',
    ],
    tip: "Keep your ribs down — don't flare them to cheat the rep.",
    eq: ['dumbbell', 'bench'],
    alt: ['Overhead Press'],
    vid: 'rO_iEImwHyo',
  },
  'Lateral Raise': {
    m: 'Side delts',
    sr: '3 × 12–15',
    steps: [
      'Stand with light dumbbells at your sides, slight bend in the elbows.',
      'Raise the weights out to the sides, leading with your elbows.',
      'Stop at shoulder height, pause briefly, lower slowly.',
    ],
    tip: "Go light. If you're swinging, the weight is too heavy.",
    eq: ['dumbbell'],
    alt: ['Face Pull'],
    vid: '4hTUCDUQaNA',
  },
  'Rear Delt Fly': {
    m: 'Rear delts · Upper back',
    sr: '3 × 12–15',
    steps: [
      'Hinge forward at the hips with a flat back, dumbbells hanging below you.',
      'Raise the weights out to the sides with a slight elbow bend.',
      'Squeeze your shoulder blades at the top, lower slowly.',
    ],
    tip: 'Think about pulling your arms apart, not lifting the weight up.',
    eq: ['dumbbell'],
    alt: ['Face Pull'],
    vid: 'LsT-bR_zxLo',
  },
  'Tricep Pushdown': {
    m: 'Triceps',
    sr: '3 × 10–12',
    steps: [
      'Face a cable machine with a bar or rope at chest height.',
      'Pin your elbows to your sides and push down until arms are straight.',
      'Squeeze at the bottom, then let the weight rise to about 90° at the elbow.',
    ],
    tip: 'If your elbows drift forward, drop the weight.',
    eq: ['cable'],
    att: [
      'Rope — splits at the bottom for a fuller squeeze',
      'Straight bar — slightly heavier loading',
      'V-bar — easiest on the wrists',
    ],
    alt: ['Skullcrusher', 'Dips'],
    vid: '1FjkhpZsaxc',
  },
  Skullcrusher: {
    m: 'Triceps (long head)',
    sr: '3 × 10–12',
    steps: [
      'Lie on a bench holding an EZ-bar or dumbbells over your chest.',
      'Keeping upper arms still, bend the elbows to lower the weight toward your forehead.',
      'Extend back up without letting the elbows flare wide.',
    ],
    tip: 'Lower the bar slightly behind your head for a bigger stretch.',
    eq: ['barbell', 'bench'],
    alt: ['Tricep Pushdown', 'Dips'],
    vid: 'YUTJAt0vIGY',
  },
  Dips: {
    m: 'Chest · Triceps · Front delts',
    sr: '3 × 8–12',
    steps: [
      'Support yourself on parallel bars with arms locked out.',
      'Lean slightly forward and lower until shoulders are just below elbows.',
      'Press back up without locking out aggressively.',
    ],
    tip: 'Lean forward for chest emphasis, stay upright for triceps.',
    eq: ['pullupbar'],
    alt: ['Push-Up'],
    vid: 'Gz8NkGoNPkc',
  },
  'Push-Up': {
    m: 'Chest · Triceps · Core',
    sr: '3 × max reps',
    steps: [
      'Start in a plank with hands just outside shoulder width.',
      'Lower your whole body as one unit until your chest nearly touches the floor.',
      'Press back up keeping your hips in line with your shoulders.',
    ],
    tip: 'A sagging lower back means your core gave out — stop the set.',
    eq: [],
    alt: [],
    vid: 'I9fsqKE5XHo',
  },
  'Cable Fly': {
    m: 'Chest',
    sr: '3 × 12–15',
    steps: [
      'Set cables at chest height and take a step forward, one foot ahead.',
      'With a slight elbow bend, bring your hands together in a hugging arc.',
      'Squeeze the chest at the middle, then open back slowly to a stretch.',
    ],
    tip: "Keep the same elbow angle throughout — it's a fly, not a press.",
    eq: ['cable'],
    att: ['D-handles — the only attachment you need here'],
    alt: ['Incline Dumbbell Press', 'Push-Up'],
    vid: 'I-Ue34qLxc4',
  },
  Deadlift: {
    m: 'Posterior chain · Back · Grip',
    sr: '3 × 4–6',
    steps: [
      'Stand with the bar over mid-foot, shins about an inch away.',
      'Hinge down and grip just outside your legs, flat back, chest up.',
      'Push the floor away and stand tall, keeping the bar against your legs.',
      'Lock out with squeezed glutes, then lower by pushing your hips back.',
    ],
    tip: 'Treat every rep like the first one — reset your brace each time.',
    eq: ['barbell'],
    alt: ['Romanian Deadlift', 'Hip Thrust'],
    vid: 'XxWcirHIwVo',
    lower: true,
  },
  'Romanian Deadlift': {
    m: 'Hamstrings · Glutes · Lower back',
    sr: '3 × 8–10',
    steps: [
      'Hold the bar at hip level with a shoulder-width grip.',
      'Push your hips straight back with soft knees, sliding the bar down your thighs.',
      'Stop when you feel a deep hamstring stretch (usually mid-shin).',
      'Drive your hips forward to stand back up.',
    ],
    tip: "It's a hip hinge, not a squat — your knees barely move.",
    eq: ['barbell'],
    alt: ['Hip Thrust', 'Lying Leg Curl'],
    vid: '5bJEigM5iVg',
    lower: true,
  },
  'Pull-Up': {
    m: 'Lats · Biceps · Upper back',
    sr: '3 × max reps',
    steps: [
      'Hang from a bar with hands just outside shoulder width, palms away.',
      'Pull your chest toward the bar by driving your elbows down.',
      'Get your chin over the bar, then lower all the way to a dead hang.',
    ],
    tip: "Can't do one yet? Use a band or do slow negatives — they build fast.",
    eq: ['pullupbar'],
    alt: ['Lat Pulldown', 'Barbell Row'],
    vid: 'eGo4IYlbE5g',
  },
  'Lat Pulldown': {
    m: 'Lats · Biceps',
    sr: '3 × 10–12',
    steps: [
      'Sit with thighs locked under the pads, grip wide on the bar.',
      'Pull the bar to your upper chest while leaning back slightly.',
      'Squeeze your lats, then let the bar rise with full arm extension.',
    ],
    tip: 'Pull with your elbows, not your hands — imagine elbows going into your pockets.',
    eq: ['cable'],
    att: [
      'Wide lat bar — best for back width',
      'Neutral V-grip — more mid-back, wrist friendly',
      'Underhand close bar — extra biceps',
    ],
    alt: ['Pull-Up'],
    vid: 'SALxEARiMkw',
  },
  'Barbell Row': {
    m: 'Mid-back · Lats · Biceps',
    sr: '4 × 8–10',
    steps: [
      'Hinge to about 45° with a flat back, bar hanging at arm’s length.',
      'Pull the bar to your lower ribs, elbows tracking back.',
      'Pause, then lower under control without standing up between reps.',
    ],
    tip: 'If your torso bounces up every rep, lighten the load.',
    eq: ['barbell'],
    alt: ['Seated Cable Row'],
    vid: 'A1tmBJKKfVs',
  },
  'Seated Cable Row': {
    m: 'Mid-back · Lats · Biceps',
    sr: '3 × 10–12',
    steps: [
      'Sit tall with feet braced, grab the handle with arms extended.',
      'Pull the handle to your stomach, squeezing your shoulder blades together.',
      'Let your arms extend fully and shoulders stretch forward slightly.',
    ],
    tip: "Chest stays proud — don't turn it into a crunch.",
    eq: ['cable'],
    att: [
      'V-bar (close grip) — best all-rounder',
      'Wide bar — upper back emphasis',
      'Rope — longest range of motion',
    ],
    alt: ['Barbell Row'],
    vid: 'vwHG9Jfu4sw',
  },
  'Face Pull': {
    m: 'Rear delts · Rotator cuff',
    sr: '3 × 15',
    steps: [
      'Set a rope attachment at face height on a cable machine.',
      'Pull the rope toward your face, splitting the ends past your ears.',
      'Finish with elbows high and hands beside your head, then return slowly.',
    ],
    tip: "Great for posture and shoulder health — don't skip it.",
    eq: ['cable'],
    att: ['Rope — the only attachment that works properly here'],
    alt: ['Rear Delt Fly'],
    vid: 'IeOqdw9WI90',
  },
  'Barbell Shrug': {
    m: 'Traps',
    sr: '3 × 12–15',
    steps: [
      'Hold a barbell at hip level with straight arms.',
      'Shrug your shoulders straight up toward your ears.',
      'Hold the squeeze for a second, then lower fully.',
    ],
    tip: 'Straight up and down — rolling the shoulders adds nothing.',
    eq: ['barbell'],
    alt: [],
    vid: 'MlqHEfydPpE',
  },
  'Barbell Curl': {
    m: 'Biceps',
    sr: '3 × 8–12',
    steps: [
      'Stand holding the bar with an underhand, shoulder-width grip.',
      'Curl the bar up keeping elbows pinned to your sides.',
      'Squeeze at the top, lower slowly to full extension.',
    ],
    tip: 'The lowering half builds just as much muscle — take 2–3 seconds down.',
    eq: ['barbell'],
    alt: ['Hammer Curl'],
    vid: 'ZQWL7omZh94',
  },
  'Hammer Curl': {
    m: 'Biceps · Forearms',
    sr: '3 × 10–12',
    steps: [
      'Hold dumbbells at your sides with palms facing each other.',
      'Curl both up keeping that neutral grip the whole way.',
      'Lower under control without swinging.',
    ],
    tip: 'Hits the brachialis — makes arms look thicker from the side.',
    eq: ['dumbbell'],
    alt: ['Barbell Curl'],
    vid: 'BRVDS6HVR9Q',
  },
  'Preacher Curl': {
    m: 'Biceps',
    sr: '3 × 10–12',
    steps: [
      'Rest your upper arms flat on the preacher pad, gripping an EZ-bar.',
      'Curl up until forearms are vertical.',
      'Lower slowly until arms are almost fully straight.',
    ],
    tip: "Don't fully relax at the bottom — keep tension on the muscle.",
    eq: ['machine'],
    alt: ['Barbell Curl'],
    vid: '7ixqAPO6JvU',
  },
  'Barbell Back Squat': {
    m: 'Quads · Glutes · Core',
    sr: '4 × 6–8',
    steps: [
      'Set the bar on your upper traps, grip tight, stand with feet shoulder width.',
      'Brace your core, then sit down and back, knees tracking over toes.',
      'Descend until thighs are at least parallel to the floor.',
      'Drive up through your whole foot back to standing.',
    ],
    tip: 'Big breath into your belly before every rep — your brace is your seatbelt.',
    eq: ['barbell'],
    alt: ['Leg Press', 'Walking Lunge'],
    vid: 'gcNh17Ckjgg',
    lower: true,
  },
  'Front Squat': {
    m: 'Quads · Core · Upper back',
    sr: '3 × 6–8',
    steps: [
      'Rest the bar on your front delts with elbows high, fingertips under the bar.',
      'Squat down keeping your torso as upright as possible.',
      'Hit depth, then drive up while keeping those elbows lifted.',
    ],
    tip: 'If your elbows drop, the bar rolls forward — elbows up is rule one.',
    eq: ['barbell'],
    alt: ['Leg Press'],
    vid: 'v-mQm_droHg',
    lower: true,
  },
  'Leg Press': {
    m: 'Quads · Glutes',
    sr: '3 × 10–12',
    steps: [
      'Sit in the machine with feet shoulder width on the platform.',
      'Lower the sled until knees reach about 90° without your lower back rounding off the pad.',
      'Press back up, stopping just short of locking the knees.',
    ],
    tip: 'Never let your hips curl up off the seat at the bottom.',
    eq: ['machine'],
    alt: ['Barbell Back Squat', 'Walking Lunge'],
    vid: 'nDh_BlnLCGc',
    lower: true,
  },
  'Walking Lunge': {
    m: 'Quads · Glutes · Balance',
    sr: '3 × 10 per leg',
    steps: [
      'Hold dumbbells at your sides and step forward into a lunge.',
      'Lower until your back knee nearly touches the floor.',
      'Push through the front foot and step straight into the next lunge.',
    ],
    tip: 'Take a slightly wider stance for balance — like walking on train tracks, not a tightrope.',
    eq: [],
    alt: [],
    vid: 'Pbmj6xPo-Hw',
    lower: true,
  },
  'Leg Extension': {
    m: 'Quads',
    sr: '3 × 12–15',
    steps: [
      "Sit with the pad on your shins, knees lined up with the machine's pivot.",
      'Extend your legs until straight, squeezing the quads hard.',
      'Lower slowly without letting the stack slam.',
    ],
    tip: 'Pause for one second at the top of every rep.',
    eq: ['machine'],
    alt: ['Walking Lunge'],
    vid: 'ztNBgrGy6FQ',
    lower: true,
  },
  'Lying Leg Curl': {
    m: 'Hamstrings',
    sr: '3 × 10–12',
    steps: [
      'Lie face down with the pad just above your heels.',
      'Curl your heels toward your glutes.',
      'Lower slowly to a full stretch without your hips lifting.',
    ],
    tip: 'Point your toes to make the hamstrings do more of the work.',
    eq: ['machine'],
    alt: ['Romanian Deadlift'],
    vid: 'jxctD6fL_FQ',
    lower: true,
  },
  'Standing Calf Raise': {
    m: 'Calves',
    sr: '4 × 12–15',
    steps: [
      'Stand with the balls of your feet on a step, heels hanging off.',
      'Lower your heels for a deep stretch.',
      'Rise as high as you can onto your toes and hold for a second.',
    ],
    tip: 'Full stretch at the bottom matters more than the weight.',
    eq: [],
    alt: [],
    vid: 'sNqa1ad2qIQ',
    lower: true,
  },
  'Hip Thrust': {
    m: 'Glutes · Hamstrings',
    sr: '3 × 8–12',
    steps: [
      'Sit with your upper back on a bench, barbell over your hips.',
      'Drive through your heels and lift your hips until your body is a straight line.',
      'Squeeze your glutes hard at the top, then lower with control.',
    ],
    tip: 'Tuck your chin and look forward — it keeps your ribs down.',
    eq: ['barbell', 'bench'],
    alt: ['Walking Lunge'],
    vid: 'S_uZP4UH6J0',
    lower: true,
  },
  Plank: {
    m: 'Core',
    sr: '3 × 45–60 sec',
    steps: [
      'Set up on forearms and toes, body in one straight line.',
      "Squeeze your glutes and brace your abs like you're about to be poked.",
      'Breathe steadily and hold without letting your hips sag or pike.',
    ],
    tip: 'A shorter, harder plank beats a long, saggy one.',
    eq: [],
    alt: [],
    vid: 'v25dawSzRTM',
  },
  'Goblet Squat': {
    m: 'Quads · Glutes · Core',
    sr: '3 × 10–12',
    steps: [
      'Hold one dumbbell vertically against your chest with both hands.',
      'Squat down between your knees, keeping your chest tall.',
      'Hit full depth, then drive back up through your whole foot.',
    ],
    tip: 'The weight at your chest acts as a counterbalance — most people squat deeper this way.',
    eq: ['dumbbell'],
    alt: ['Barbell Back Squat'],
    vid: 'lRYBbchqxtI',
    lower: true,
  },
  'Dumbbell Romanian Deadlift': {
    m: 'Hamstrings · Glutes',
    sr: '3 × 10–12',
    steps: [
      'Hold dumbbells resting against the front of your thighs, soft bend in the knees.',
      'Push your hips back, sliding the dumbbells down your legs with a flat back.',
      'Stop at a deep hamstring stretch, then drive your hips forward to stand tall.',
    ],
    tip: 'Keep the dumbbells brushing your legs the whole way down.',
    eq: ['dumbbell'],
    alt: ['Romanian Deadlift'],
    vid: 'hQgFixeXdZo',
    lower: true,
  },
  'Dumbbell Bench Press': {
    m: 'Chest · Triceps · Front delts',
    sr: '4 × 8–10',
    steps: [
      'Sit on a flat bench with a dumbbell on each knee, then lie back kicking them to the start.',
      'Press the dumbbells over your chest with palms facing forward.',
      'Lower under control until they are level with your chest, elbows ~45°.',
      'Press back up and squeeze the chest at the top.',
    ],
    tip: 'Dumbbells let each side work independently and stretch the chest further than a bar.',
    eq: ['dumbbell', 'bench'],
    alt: ['Barbell Bench Press', 'Push-Up'],
    vid: 'SzcSrpVr0GA',
  },
  'Incline Barbell Press': {
    m: 'Upper chest · Front delts · Triceps',
    sr: '4 × 6–8',
    steps: [
      'Set a bench to about 30°, lie back with eyes under the bar.',
      'Grip just outside shoulder width and unrack with straight arms.',
      'Lower the bar to your upper chest, just below the collarbone.',
      'Press back up over the shoulders without flaring the elbows.',
    ],
    tip: 'Keep the incline low (~30°) — steeper turns it into a shoulder press.',
    eq: ['barbell', 'bench'],
    alt: ['Incline Dumbbell Press', 'Barbell Bench Press'],
    vid: 'SrqOu55lrYU',
  },
  'Close-Grip Bench Press': {
    m: 'Triceps · Chest · Front delts',
    sr: '3 × 8–10',
    steps: [
      'Lie on a flat bench and grip the bar about shoulder-width apart.',
      'Unrack and lower the bar to your lower chest, keeping elbows tucked close.',
      'Press up by extending the elbows, keeping the bar over the lower chest.',
    ],
    tip: 'Tucked elbows put the work on the triceps — do not flare them out.',
    eq: ['barbell', 'bench'],
    alt: ['Tricep Pushdown', 'Skullcrusher', 'Dips'],
    vid: 'xXd7sddHGa0',
  },
  'Dumbbell Row': {
    m: 'Lats · Upper back · Biceps',
    sr: '3 × 10–12',
    steps: [
      'Place one knee and hand on a bench, other foot on the floor, dumbbell hanging.',
      'Keep a flat back and pull the dumbbell to your hip, leading with the elbow.',
      'Squeeze the back at the top, then lower under control to a full stretch.',
    ],
    tip: 'Row to your hip, not your shoulder, and avoid twisting your torso.',
    eq: ['dumbbell', 'bench'],
    alt: ['Barbell Row', 'Seated Cable Row'],
    vid: 'gfUg6qWohTk',
  },
  'T-Bar Row': {
    m: 'Upper back · Lats · Biceps',
    sr: '3 × 8–12',
    steps: [
      'Straddle the bar, hinge at the hips with a flat back and grab the handles.',
      'Pull the weight to your chest, driving the elbows back and squeezing the shoulder blades.',
      'Lower under control to a full stretch without rounding your back.',
    ],
    tip: 'Keep your chest up and hips back — let the mid-back do the work.',
    eq: ['barbell'],
    alt: ['Barbell Row', 'Seated Cable Row'],
    vid: 'TyLoy3n_a10',
  },
  'Bulgarian Split Squat': {
    m: 'Quads · Glutes · Hamstrings',
    sr: '3 × 10–12',
    steps: [
      'Stand a stride in front of a bench, lacing the top of your rear foot on it.',
      'Bend the front knee to lower straight down until the front thigh is parallel.',
      'Drive through the front heel to stand back up; finish all reps, then switch legs.',
    ],
    tip: 'Most of your weight stays on the front leg — the back leg is just for balance.',
    eq: ['dumbbell', 'bench'],
    alt: ['Walking Lunge', 'Leg Press'],
    vid: 'hiLF_pF3EJM',
    lower: true,
  },
  'Hack Squat': {
    m: 'Quads · Glutes',
    sr: '3 × 10–12',
    steps: [
      'Set your shoulders and back against the hack-squat pads, feet mid-platform.',
      'Unlock the safeties and lower until your thighs are at least parallel.',
      'Drive through your whole foot to push back up, without locking the knees hard.',
    ],
    tip: 'A higher foot position hits glutes more; lower and closer hits the quads.',
    eq: ['machine'],
    alt: ['Barbell Back Squat', 'Leg Press'],
    vid: 'Zgd6eFxPTxM',
    lower: true,
  },
  'Seated Calf Raise': {
    m: 'Calves',
    sr: '4 × 12–15',
    steps: [
      'Sit with the balls of your feet on the platform and the pad over your knees.',
      'Lower your heels for a deep stretch in the calves.',
      'Drive up onto your toes as high as possible and squeeze at the top.',
    ],
    tip: 'The bent knee targets the soleus — go slow and get a full stretch each rep.',
    eq: ['machine'],
    alt: ['Standing Calf Raise'],
    vid: '6O5hh1rBtx8',
    lower: true,
  },
  'Cable Crunch': {
    m: 'Abs · Core',
    sr: '3 × 12–15',
    steps: [
      'Kneel below a high cable holding a rope at the sides of your head.',
      'Crunch down by rounding your spine, bringing your elbows toward your thighs.',
      'Squeeze the abs hard at the bottom, then return under control.',
    ],
    tip: 'Move from your spine, not your hips — think about curling your ribs to your pelvis.',
    eq: ['cable'],
    att: ['Rope — best for crunching down', 'Single handle — one side at a time'],
    alt: ['Plank', 'Hanging Leg Raise'],
    vid: 'dkGwcfo9zto',
  },
  'Hanging Leg Raise': {
    m: 'Abs · Core · Hip flexors',
    sr: '3 × 10–15',
    steps: [
      'Hang from a pull-up bar with a shoulder-width grip, body still.',
      'Without swinging, raise your legs until your thighs are at least parallel.',
      'Lower slowly under control and avoid using momentum.',
    ],
    tip: 'Bend the knees if straight legs are too hard, and kill any swinging.',
    eq: ['pullupbar'],
    alt: ['Cable Crunch', 'Plank'],
    vid: 'Pr1ieGZ5atk',
  },
  'Overhead Tricep Extension': {
    m: 'Triceps',
    sr: '3 × 10–12',
    steps: [
      'Hold a dumbbell or rope overhead with the elbows pointing up.',
      'Lower the weight behind your head by bending only at the elbows.',
      'Extend back up to lockout, keeping the upper arms still.',
    ],
    tip: 'The overhead position stretches the long head of the triceps for more growth.',
    eq: ['dumbbell'],
    att: [
      'Rope on a low cable — constant tension',
      'Single dumbbell — simplest',
      'EZ bar — heavier loading',
    ],
    alt: ['Skullcrusher', 'Tricep Pushdown'],
    vid: '-Vyt2QdsR7E',
  },
  'Incline Dumbbell Curl': {
    m: 'Biceps',
    sr: '3 × 10–12',
    steps: [
      'Sit back on an incline bench with a dumbbell in each hand, arms hanging.',
      'Curl the dumbbells up without moving your elbows forward.',
      'Squeeze at the top, then lower all the way to a full stretch.',
    ],
    tip: 'The incline puts the biceps on stretch — keep your elbows behind your body.',
    eq: ['dumbbell', 'bench'],
    alt: ['Barbell Curl', 'Hammer Curl'],
    vid: 'DCe8f6vMe9A',
  },
  'EZ Bar Curl': {
    m: 'Biceps · Forearms',
    sr: '3 × 8–12',
    steps: [
      'Hold an EZ bar at the angled grips, elbows at your sides.',
      'Curl the bar up by flexing the biceps, keeping the elbows pinned.',
      'Lower under control to a full stretch.',
    ],
    tip: 'The angled grip is easier on the wrists than a straight bar.',
    eq: ['barbell'],
    alt: ['Barbell Curl', 'Preacher Curl'],
    vid: 'd2r5TCqnR4Y',
  },
  'Concentration Curl': {
    m: 'Biceps',
    sr: '3 × 12–15',
    steps: [
      'Sit on a bench, brace your elbow against the inside of your thigh, dumbbell hanging.',
      'Curl the dumbbell up toward your shoulder, squeezing hard at the top.',
      'Lower slowly to a full stretch and repeat, then switch arms.',
    ],
    tip: 'Bracing the elbow isolates the biceps — no swinging or body english.',
    eq: ['dumbbell'],
    alt: ['Preacher Curl', 'Barbell Curl'],
    vid: 'EjUnEEfTSEY',
  },
  'Cable Crossover': {
    m: 'Chest · Front delts',
    sr: '3 × 12–15',
    steps: [
      'Set both pulleys high, grab a handle in each hand and step forward into a stagger.',
      'With a slight elbow bend, bring your hands together in front of your chest.',
      'Squeeze the chest, then let the hands travel back to a stretch under control.',
    ],
    tip: 'Lead with your elbows and think about hugging — keep tension on the chest throughout.',
    eq: ['cable'],
    att: ['D-handles — best feel and stretch', 'Single handle — one side at a time'],
    alt: ['Cable Fly', 'Incline Dumbbell Press'],
    vid: 'A6ch0UN4SHs',
  },
  'Reverse Lunge': {
    m: 'Quads · Glutes · Hamstrings',
    sr: '3 × 10–12',
    steps: [
      'Stand tall holding dumbbells, then step one foot back into a lunge.',
      'Lower until both knees are about 90°, front shin vertical.',
      'Drive through the front heel to return to standing, then alternate legs.',
    ],
    tip: 'Stepping back is easier on the knees than a forward lunge and keeps tension on the front leg.',
    eq: ['dumbbell'],
    alt: ['Walking Lunge', 'Bulgarian Split Squat'],
    vid: 'TI2U-RfbALY',
    lower: true,
  },
  'Sumo Deadlift': {
    m: 'Glutes · Hamstrings · Quads · Back',
    sr: '4 × 4–6',
    steps: [
      'Take a wide stance with toes pointed out, grip the bar inside your knees.',
      'Drop your hips, chest up, and drive your feet out into the floor to break the bar off.',
      'Stand tall by squeezing the glutes, then lower under control.',
    ],
    tip: 'The wider stance shortens the range and lets you stay more upright than a conventional pull.',
    eq: ['barbell'],
    alt: ['Deadlift', 'Romanian Deadlift'],
    vid: 'JF3iwfK5WI0',
    lower: true,
  },

  // ── Mobility & stretching ────────────────────────────────────────────────
  "World's Greatest Stretch": {
    m: 'Hamstrings · Hips · Quads',
    sr: '2 × 5 per side',
    steps: [
      'Step into a deep forward lunge and place both hands on the floor inside the front foot.',
      'Drive the front knee outward, then rotate your chest toward the front leg and reach that arm to the ceiling.',
      'Bring the hand back down and straighten the front leg to feel the hamstring.',
      'Step back, switch legs, and repeat.',
    ],
    tip: 'Move slowly and breathe — chase a little more rotation each rep, not speed.',
    eq: [],
    alt: ['Groiner Stretch', 'Hip Flexor Stretch'],
    vid: '-CiWQ2IvY34',
    mobility: true,
  },
  'Standing Hip Circles': {
    m: 'Glutes · Hips',
    sr: '2 × 10 per side',
    steps: [
      'Stand tall and balance on one leg, holding a wall or rail if you need to.',
      'Lift the other knee to hip height in front of you.',
      'Open the knee out to the side in a slow, controlled circle, then bring it back.',
      'Finish the set, then switch legs and circle the other way.',
    ],
    tip: 'Keep your torso upright — let the movement come from the hip, not by leaning.',
    eq: [],
    alt: ["World's Greatest Stretch", 'Hip Flexor Stretch'],
    vid: 'OqR7Tl6SPLQ',
    mobility: true,
  },
  'Groiner Stretch': {
    m: 'Glutes · Hips · Hamstrings',
    sr: '2 × 8 per side',
    steps: [
      'Start in a push-up position with your hands under your shoulders.',
      'Step one foot up to the outside of the same-side hand.',
      'Sink your hips toward the floor to open the groin and hip, then step back.',
      'Alternate sides each rep.',
    ],
    tip: 'Keep the back leg straight and the back heel reaching away for a fuller stretch.',
    eq: [],
    alt: ["World's Greatest Stretch", 'Lying Glute Stretch'],
    vid: 'vRH5wywUefI',
    mobility: true,
  },
  'Hip Flexor Stretch': {
    m: 'Quads · Hips',
    sr: '2 × 30s per side',
    steps: [
      'Kneel on one knee with the other foot planted in front, both bent about 90°.',
      'Tuck your tailbone under and squeeze the glute of the down leg.',
      'Glide your hips gently forward until you feel a stretch at the front of the hip.',
      'Hold and breathe, then switch sides.',
    ],
    tip: 'The glute squeeze is what actually lengthens the hip flexor — not just leaning forward.',
    eq: [],
    alt: ['Lying Glute Stretch', 'Standing Hip Circles'],
    vid: '34SlL-PPCWQ',
    mobility: true,
  },
  'Lying Glute Stretch': {
    m: 'Glutes · Hips',
    sr: '2 × 30s per side',
    steps: [
      'Lie on your back and cross one ankle over the opposite knee to make a figure-4.',
      'Reach through and hold behind the supporting thigh.',
      'Draw the thigh toward your chest until you feel a stretch in the glute.',
      'Hold and breathe, then switch sides.',
    ],
    tip: 'Keep the crossed-leg knee pressed open and your head relaxed on the floor.',
    eq: [],
    alt: ['Hip Flexor Stretch', 'Groiner Stretch'],
    vid: 'YBV6d5TluFA',
    mobility: true,
  },
  'Cat-Cow Stretch': {
    m: 'Back · Core',
    sr: '2 × 10 reps',
    steps: [
      'Start on all fours with hands under shoulders and knees under hips.',
      'Exhale and round your spine toward the ceiling, tucking your chin (cat).',
      'Inhale and drop your belly, lifting your chest and tailbone (cow).',
      'Flow smoothly between the two with your breath.',
    ],
    tip: 'Let your breath set the pace — exhale to round, inhale to arch.',
    eq: [],
    alt: ['Lying Glute Stretch', 'Hip Flexor Stretch'],
    vid: 'vuyUwtHl694',
    mobility: true,
  },
};

export const EXERCISE_NAMES = Object.keys(EX);

export function getExercise(name: string): Exercise | undefined {
  return EX[name];
}

/** YouTube search fallback for movements without a bundled video. */
export const ytSearch = (name: string): string =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent(name + ' proper form tutorial')}`;
